Add HTTP basic authentication support
nypublicradio/audiogram pull request #68
Opened 2016-12-11 15:23 UTC by rob

Hey - not sure if this is something you would want to include by default in Audiogram, but we are going to be using Audiogram here at [WNPR](http://wnpr.org) and wanted some basic form of authentication since the URL would be public.

This PR adds HTTP basic authentication support using the `http-auth` module. If `settings/users.htpasswd` exists and isn't empty, the module will load and the site will be protected using the logins contained in the file. If it doesn't exist, nothing will load or happen. So you don't have to configure any settings, etc - it's all based on this file.

It also ignores any requests to `/video/*`, so if you decide to share the URL Audiogram generates (and aren't using S3) it won't ask for a password or anything when trying to view the video.

(`settings/users.htpasswd` is just a regular [htpasswd](https://httpd.apache.org/docs/current/programs/htpasswd.html) file.)

2016-12-13 20:39 UTC, veltman commented
Thanks for contributing this! I'm into it. I think ideally I'd make two changes:

1. Make the .htpasswd file location something specified in `settings/index.js` rather than hardcoded. This would also eliminate the need for a try/catch.

2. Move the auth middleware into a different file, maybe `server/auth.js`, so that any other auth strategies can accumulate there.

So would end up with something like:

index.js
```js
if (serverSettings.htpasswd) {
  app.use(/^\/((?!video).)*/, require("./auth.js")(serverSettings.htpasswd));
}
```

auth.js
```js
var fs = require("fs"),
    auth = require("http-auth");

module.exports = function(htpasswdPath){

  var basic = auth.basic({
    file: fs.readFileSync(htpasswdPath, "utf8"),
    realm:  "Audiogram Administration",
    msg401: "Error: Your account details could not be authenticated."
  });

  return function(req, res, next) {
    (auth.connect(basic))(req, res, next);
  }

};
```

What do you think about those? Any objection?

2016-12-13 20:50 UTC, rob commented
@veltman 

You're right, those changes sound good! I should have thought of that. I'll get them committed tonight.

(This is my first time using Node / Express in the "real world" coming from PHP, so I've just been learning as I go regarding best practices...)

2016-12-14 16:27 UTC, rob commented
@veltman 

Should be all set. Also added some docs explaining the new option (let me know if I should change the wording...)

2016-12-14 17:56 UTC, veltman requested changes
Two other changes we should probably add to this:

1. Update `lib/settings/validate-settings.js` so that it makes sure `authFile` is an absolute path, and warns if the file doesn't exist (similar to how it validates font files: https://github.com/nypublicradio/audiogram/blob/master/lib/settings/validate-settings.js#L61-L67).
2. Add a few tests in `test/server-test.js` - maybe one for an invalid username/password, one for a valid pair, one for a video.

Do you want to take a crack at either of those? I'm also happy to pull this down and work on that if not. Thanks again for your help!

2016-12-14 17:56 UTC, veltman commented on server/auth.js
> +  return function(req, res, next) {
Looking at the http-auth docs, I think this can be reduced to:

```js
return auth.connect(basic);
```

2016-12-14 17:56 UTC, veltman commented on SERVER.md
> +  authFile: path.join(__dirname) + '/users.htpasswd'
This example should probably either be:

```js
  authFile: path.join(__dirname, "users.htpasswd")
```

or:

```js
  authFile: "settings/users.htpasswd"
```

2016-12-14 17:56 UTC, veltman commented on SERVER.md
> +`authFile` - the location of a htpasswd auth file. If set, the entire site will use HTTP basic authentication. However, generated video URLs (/video/\*) will remain public and sharable without any au
Could get rid of the backslash?

2016-12-14 17:56 UTC, veltman commented on settings/index.js
> +  authFile - location of a htpasswd auth file. If set, the entire site will use HTTP basic authentication (aside from sharable /video/* URLs)
Could we link "htpasswd auth file" to some sort of explanation of the format? Maybe the Apache docs: https://httpd.apache.org/docs/current/programs/htpasswd.html

2016-12-14 19:58 UTC, rob commented
@veltman 

Take a look, I did everything except for the tests. Do you think you could write those?

If not, I just have to look into tape/supertest some more. Looks fairly easy. Just let me know.

2017-01-05 18:33 UTC, veltman commented
I've added some tests, the issue now is that the `http-auth` module uses ES6 syntax so it would bump the minimum Node version required from v0.12 up to about v4.x. Need to think about this a bit.  Not really a big deal but does create some annoyance especially with old package managers.

2017-01-05 18:46 UTC, rob commented
@veltman 

According to [this](https://github.com/nodejs/LTS), v0.12 just reached its EOL/maintenance period on 2016-12-31 so maybe it's for the best to bump it to v4.

2017-01-05 21:00 UTC, veltman commented
Yeah, I'm OK with changing the requirements generally, my concern is with existing installs/forks. Merging this means that if someone pulls down the latest version to update at any point, it may be a breaking change. I think at a minimum I should probably add a version check and a plain English message about it somewhere.

2017-01-13 00:07 UTC, rob commented
@veltman 

Everything seems to work for me; do you need me to do anything else with this PR? Thanks for helping out! :-)

rob

2019-08-22 22:03 UTC, closed without merging